#Deriving the latest base image
FROM python:latest



# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR C:/Users/ASUS/Desktop/Erasmus Masters/SA/project
#to COPY the remote file at working directory in container
COPY analyzer.py ./
# Now the structure looks like this '/usr/app/src/test.py'
RUN pip install paho-mqtt
#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

CMD [ "python", "./analyzer.py"]